# Generated by Django 4.1.7 on 2023-03-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseideineruser',
            name='posts_liked',
            field=models.ManyToManyField(related_name='liked_by', to='backend.idea'),
        ),
    ]
