# Generated by Django 4.1.7 on 2023-03-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinedusers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='likestoideas',
            name='user',
        ),
        migrations.AddField(
            model_name='joinedusers',
            name='autor',
            field=models.CharField(default='', max_length=22, verbose_name='Никнейм'),
        ),
        migrations.AddField(
            model_name='likestoideas',
            name='autor',
            field=models.CharField(default='', max_length=22, verbose_name='Никнейм'),
        ),
    ]
