# Generated by Django 3.2.16 on 2023-03-12 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='nickname',
            field=models.CharField(default='', max_length=40, verbose_name='ник'),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='registrationdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopuser',
            name='surname',
            field=models.CharField(default='', max_length=40, verbose_name='ник'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to='users_avatars'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='email',
            field=models.CharField(default='', max_length=40, verbose_name='ник'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='password',
            field=models.CharField(default='', max_length=40, verbose_name='ник'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='username',
            field=models.CharField(default='', max_length=40, unique=True, verbose_name='ник'),
        ),
    ]
