# Generated by Django 3.2.16 on 2023-03-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0002_auto_20230312_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='email',
            field=models.CharField(default='', max_length=40, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='password',
            field=models.CharField(default='', max_length=40, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='surname',
            field=models.CharField(default='', max_length=40, verbose_name='surname'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='username',
            field=models.CharField(default='', max_length=40, unique=True, verbose_name='username'),
        ),
    ]
