# Generated by Django 3.2.16 on 2023-03-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0005_alter_shopuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
